"""
issue_area_matcher.py

Core engine for detecting Issue Areas and their subsequent Subtopics 
using the new exact matching framework.
Operates on the configuration generated by `generate_issue_area_topics.py`.

Logic Flow:
  1. Determine Parent Issue Areas:
     - Exact Match (spaCy) OR Semantic Match (SentenceTransformers)
     - Filter by Colocation requirements
     - Filter by Exclusionary terms
  2. Determine valid Subtopics:
     - ONLY evaluate subtopics belonging to the successfully matched Issue Areas
     - Exact Match (spaCy) OR Semantic Match (SentenceTransformers)
     - Filter by Subtopic exclusionary terms
"""

import json
import os
import sys
import spacy
from spaczz.matcher import FuzzyMatcher
from sentence_transformers import SentenceTransformer, util

class IssueAreaMatcher:
    def __init__(
        self,
        topics_file='issue_area_topics.json',
        similarity_threshold=0.7,
        min_fuzzy_ratio=85,
        nlp_model="en_core_web_sm",
        embedding_model="all-MiniLM-L6-v2"
    ):
        """
        Loads the config, NLP components, and prepares the Matchers.
        """
        self.similarity_threshold = similarity_threshold
        self.min_fuzzy_ratio = min_fuzzy_ratio
        self.topics_file = topics_file
        
        print(f"Loading NLP models for Issue Area Matcher ({nlp_model}, {embedding_model})...")
        try:
            # Disable unused pipeline components for speed
            self.nlp = spacy.load(nlp_model, disable=["parser", "ner"])
            self.embedder = SentenceTransformer(embedding_model)
        except Exception as e:
            print(f"Error: Could not load models. Did you run setup_utils.py? {e}")
            sys.exit(1)
            
        self._load_config()

    def _load_config(self):
        """
        Reads the JSON config and builds:
         - Matchers and embeddings for Parent Issue Areas.
         - Matchers and embeddings for Subtopics.
         - Lookup dictionaries for exclusions and colocated sets.
        """
        if not os.path.exists(self.topics_file):
            print(f"Error: {self.topics_file} not found. Run generate_issue_area_topics.py first.")
            self.topics_data = []
            sys.exit(1)
            
        with open(self.topics_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            self.topics_data = data.get('topics', [])
            
        # --- PARENT ISSUE AREA SETUP ---
        self.exclusions_map = {t['issue_area']: t.get('exclusions', []) for t in self.topics_data}
        self.colocated_sets_map = {t['issue_area']: t.get('colocated_sets', []) for t in self.topics_data}
        
        self.matcher = FuzzyMatcher(self.nlp.vocab)
        self.anchor_metadata = [] 
        all_anchor_texts = []
        
        # --- SUBTOPIC SETUP ---
        self.subtopic_matcher = FuzzyMatcher(self.nlp.vocab)
        self.subtopic_anchor_metadata = []
        all_subtopic_anchor_texts = []
        self.subtopic_exclusions_map = {} # Mapping: "IssueArea::SubtopicName" -> [exclusions...]
        
        for topic in self.topics_data:
            issue_area = topic['issue_area']
            
            # Parent Patterns
            spacy_patterns = []
            for p in topic.get('patterns', []):
                spacy_patterns.append(self.nlp(p))
            if spacy_patterns:
                self.matcher.add(issue_area, spacy_patterns)
                
            # Parent Anchors
            for anchor in topic.get('anchors', []):
                all_anchor_texts.append(anchor)
                self.anchor_metadata.append((issue_area, anchor))
                
            # Subtopics config parsing
            for sub in topic.get('subtopics', []):
                subtopic_name = sub['name']
                sub_id = f"{issue_area}::{subtopic_name}" # Unique composite ID
                
                # Exclusions
                self.subtopic_exclusions_map[sub_id] = sub.get('exclusions', [])
                
                # Patterns
                sub_spacy_patterns = []
                for p in sub.get('patterns', []):
                    sub_spacy_patterns.append(self.nlp(p))
                if sub_spacy_patterns:
                    self.subtopic_matcher.add(sub_id, sub_spacy_patterns)
                    
                # Anchors
                for anchor in sub.get('anchors', []):
                    all_subtopic_anchor_texts.append(anchor)
                    # We store the parent area and the composite ID for easier logic later
                    self.subtopic_anchor_metadata.append((issue_area, sub_id, anchor))
                
        # --- PRE-COMPUTE EMBEDDINGS ---
        if all_anchor_texts:
            print(f"Pre-embedding {len(all_anchor_texts)} parent anchor phrases...")
            self.anchor_embeddings = self.embedder.encode(all_anchor_texts, convert_to_tensor=True)
        else:
            self.anchor_embeddings = None
            
        if all_subtopic_anchor_texts:
            print(f"Pre-embedding {len(all_subtopic_anchor_texts)} subtopic anchor phrases...")
            self.subtopic_anchor_embeddings = self.embedder.encode(all_subtopic_anchor_texts, convert_to_tensor=True)
        else:
            self.subtopic_anchor_embeddings = None


    def _satisfies_colocation(self, issue_area, text_lower):
        """
        Validates if the text satisfies the colocation requirements for a given Issue Area.
        If NO colocation sets are defined for the issue area, this always returns True.
        If sets ARE defined, AT LEAST ONE set must have an 'a' term AND a 'b' term present.
        """
        colocated_sets = self.colocated_sets_map.get(issue_area, [])
        if not colocated_sets:
            return True
            
        for cset in colocated_sets:
            list_a = cset["a"]
            list_b = cset["b"]
            
            has_a = any(term in text_lower for term in list_a)
            has_b = any(term in text_lower for term in list_b)
            
            if has_a and has_b:
                return True
                
        return False

    def analyze_text(self, text):
        """
        Analyzes a single piece of text and returns a tuple:
        (pipe-delimited Issue Areas, pipe-delimited Subtopics)
        """
        if not isinstance(text, str) or not text.strip():
            return (None, None)
            
        text_lower = text.lower() # Cached lowercase version for fast substring checks
        doc = self.nlp(text)
        
        # ==============================================================
        # STAGE 1: DETECT PARENT ISSUE AREAS
        # ==============================================================
        base_matched_areas = set()
        
        # Exact/Fuzzy Pattern Match (Require threshold similarity)
        matches = self.matcher(doc)
        for match_id, start, end, ratio, pattern in matches:
            if ratio >= self.min_fuzzy_ratio:
                base_matched_areas.add(match_id)
            
        # Semantic Match
        query_embedding = None # Cache this just in case we need it for subtopics too
        if self.anchor_embeddings is not None:
            query_embedding = self.embedder.encode(text, convert_to_tensor=True)
            cos_scores = util.cos_sim(query_embedding, self.anchor_embeddings)[0]
            
            for idx, score in enumerate(cos_scores):
                if score.item() >= self.similarity_threshold:
                    base_matched_areas.add(self.anchor_metadata[idx][0])
                    
        # Process Parent Filters
        final_matched_areas = set()
        for issue_area in base_matched_areas:
            if not self._satisfies_colocation(issue_area, text_lower):
                continue
            
            exclusions = self.exclusions_map.get(issue_area, [])
            if any(exc in text_lower for exc in exclusions):
                continue
                
            final_matched_areas.add(issue_area)
            
        # Short-circuit if no Issue Areas were detected
        if not final_matched_areas:
            return (None, None)
            
        # ==============================================================
        # STAGE 2: DETECT SUBTOPICS (Constrained to matched Parent Areas)
        # ==============================================================
        base_matched_subtopics = set()
        
        # Subtopic Exact/Fuzzy Pattern Match
        sub_matches = self.subtopic_matcher(doc)
        for match_id, start, end, ratio, pattern in sub_matches:
            if ratio >= self.min_fuzzy_ratio:
                sub_id = match_id # "IssueArea::Subtopic"
                parent_area = sub_id.split("::")[0]
                
                # Constraint: only consider if the parent area was assigned!
                if parent_area in final_matched_areas:
                    base_matched_subtopics.add(sub_id)
                
        # Subtopic Semantic Match
        if self.subtopic_anchor_embeddings is not None:
            if query_embedding is None:
                query_embedding = self.embedder.encode(text, convert_to_tensor=True)
                
            cos_scores = util.cos_sim(query_embedding, self.subtopic_anchor_embeddings)[0]
            for idx, score in enumerate(cos_scores):
                if score.item() >= self.similarity_threshold:
                    parent_area, sub_id, _ = self.subtopic_anchor_metadata[idx]
                    
                    # Constraint: only consider if the parent area was assigned!
                    if parent_area in final_matched_areas:
                        base_matched_subtopics.add(sub_id)
                        
        # Process Subtopic Exclusion Filters
        final_matched_subtopics = set()
        for sub_id in base_matched_subtopics:
            exclusions = self.subtopic_exclusions_map.get(sub_id, [])
            if any(exc in text_lower for exc in exclusions):
                continue
                
            # If valid, strip the parent prefix and just keep the subtopic name 
            # (or we could keep the prefix if desired, but user probably just wants the generic name)
            # Actually, sometimes users want "AI - Equity", but prompt says 
            # "testing for any subtopic associated with any assigned Issue Area".
            # We'll output the raw subtopic string.
            subtopic_name = sub_id.split("::")[1]
            final_matched_subtopics.add(subtopic_name)
            
        # Format outputs nicely
        areas_output = " | ".join(sorted(list(final_matched_areas)))
        subtopics_output = " | ".join(sorted(list(final_matched_subtopics))) if final_matched_subtopics else None
        
        return (areas_output, subtopics_output)
